language: node_js
branches:
  only:
  - main
  - "/^\\d+\\.\\d+\\.\\d+$/"  # Use sem var
# GOTCHA: Letting Travis handle `install` and `script` with default values
deploy:
  provider: heroku
  api_key:
    secure: WUF6GAGKQ6zeIKoeD99ooa1Y1q2qXXVR8iLgLVkgE3oSfMEP3UvPna2fn8seBg54yqc/XWAbbr98IKPLpGXw1MA6AEph6DIolNtTuAv7gSffnQtBq8U4+zyQACp8Ja4VQWWuR+jtzBXm0xtKU+5GvUFBkfJvzh3KQvGIc6GxTUM0/C9UTc1iKFqJvT0oEt07kAbWr8qB/cMj7ab9Fs8urob2VpWLwBo1fT+YYf4FD2XlrVStSU+0kdkj8jB2hgBb7i1yy+cqmB/LCOpb9sdFrlfU9nx8dCKzloxcVpcFDpUCmIUdBbqexXdMgevz46tMtt/Vxe+E4VFkR9Nzdk5jv4oVtfXwM0YW+s/qB1J3T9j/ksDPImi2a9c9lCnUQgQh09fIrARdUSCQOVNrNp6Wa0sx6SGTaYA6ugjg/9OQxxD/z66JL5lTZ0yKNfd2hBejfcWxfv9mlM1zqzyV9JARc3dGD9mjtex9/BzHEQ54jNFPim736vvmxNC4pwjW3ETKf2WWSp98jhNvoIJYT0sfpNI+dd49pQc1Am82Bp373+FqrbsP5+56e0jD8uzR4dpk3XLSxeNbLTf7ZkJLNq15j24nuTHQp/cjSMgB0NzlefmUI1aCR3mBc2jogQ3+3C4c7V0qwBxWmP89/REV4jtkgALgAHzbJ6MGsCd1p+2J9t4=
  app: phan-pil-bot
  on:
    tags: true
    repo: hanpeter/pil-bot
